### ISSUE TITLE
EU conversion does not seem to work. 

### ISSUE THREAD

**Issue by Mattabase** [CyclopsMC/EnergySynergy#2]
https://www.dropbox.com/s/iye5ynawt6q050y/2016-09-13_15-23-54.webm?dl=0

**Comment by rubensworks** [comment]
Note that only the conversion of Tesla/Forge _to_ RF/EU is supported, not the other way around.
This was not clear in the mod description, I've updated it now.
The other way around would involve a lot of hacking and possibly breaking mods, which is why I prefer to not do that.

I assume that Tesla was not available when you tested this? Otherwise the ID generator would be able to push energy to the EU battery. ID will support Forge Energy in the next release, so from then on, it will be able to push to EU blocks at all times.
(If Tesla _was_ present when testing this, this is a bug)

As far as I know, Ender IO does not support either Tesla or Forge Energy, so they also won't be able to push to EU blocks until they implement either one of both.

**Comment by Mattabase** [comment]
I assumed the ID Generator which is RF would have made EU

Tesla was not installed for this test correct.

**Comment by Mattabase** [comment]
So can I not take things that make RF and run Ic2 machines?

**Comment by rubensworks** [comment]
That is correct, RF producers can not power IC2 machines directly, unless that producer also emits either Tesla or Forge Energy.

You could however place a cable accepting RF and forwarding it as Tesla/FE between RF and IC2 machines, this should work.
[Fluxed Redstone](https://minecraft.curseforge.com/projects/fluxed-redstone) should be able to do this.

**Comment by rubensworks** [comment]
Closing this because this is intented behaviour, feel free to comment for further issues.
